kind: Deployment
apiVersion: apps/v1
metadata:
  name: netatmologger
  namespace: default
  labels:
    app: netatmologger

spec:
  replicas: 1
  selector:
    matchLabels:
      app: netatmologger
  template:
    metadata:
      labels:
        app: netatmologger
    spec:
      containers:
        - name: netatmologger
          image: chhenni/sww2.netatmologger:v0.1.3
          ports:
            - name: prometheus
              containerPort: 9095
          env:
            - name: Netatmo__StationId
              value: 70:ee:50:5f:58:38
            - name: Netatmo__ClientID
              value: 61530b0b5c85ad4a45354ec5
            - name: Netatmo__ClientSecret
              value: 01eIel9qpme80fRJvJOoez7MAF1HOEugfH
            - name: Netatmo__Username
              value: chhenni@gmail.com
            - name: Netatmo__Password
              value: jky9Lt?ao&S3&8
            - name: Netatmo__Endpoint
              value: https://api.netatmo.com/api/getstationsdata
            - name: Netatmo__TokenEndpoint
              value: https://api.netatmo.com/oauth2/token


---
apiVersion: v1
kind: Service
metadata:
  name: netatmologger
  namespace: default
spec:
  type: NodePort
  selector:
    app: netatmologger
  ports:
    - protocol: TCP
      port: 9095
      name: prometheus
      targetPort: 9095

